### ISSUE TITLE
Learning: TextView Practice

### ISSUE THREAD

**Issue by cnnranderson** [jesse-digregorio/AndroidTinker#1]
- [x] Change the text that appears on screen to say "This is my app!" instead of "Hello World!"
- [x] Add a new TextView to the container layout that says "Welcome!" below the "This is my app!" text.
- [x] Change the text of the "Welcome!" TextView programatically (read: not in the xml file).
- [x] Change the alignment of the "Welcome!" TextView (via xml properties)
- [x] Change the text color of either TextView to red and the font type to bold (via xml properties)

**Comment by jesse-digregorio** [comment]
finished up this practice: https://github.com/jesse-digregorio/AndroidTinker/tree/textview-practice

The odd error with "Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation" just suddenly vanished. I am a little concerned about that.
