### ISSUE TITLE
Learning: Gradle Build Dependencies

### ISSUE THREAD

**Issue by cnnranderson** [jesse-digregorio/AndroidTinker#2]
- [x] Add "ButterKnife" to your build.gradle (tip: go to the projects homepage and go to the bottom for basic instructions!)
- [x] Test that the library was imported into your project build successfully by using it to reference a view in your container layout (use one of the text views, and change it's text programmatically in the OnCreate method)

**Comment by jesse-digregorio** [comment]
checked in some changes here: https://github.com/jesse-digregorio/AndroidTinker/tree/gradle-build-dependencies

I have some questions about what was done.
