### ISSUE TITLE
Learning: String Resources

### ISSUE THREAD

**Issue by cnnranderson** [jesse-digregorio/AndroidTinker#5]
- [x] Change the name of your app in the app toolbar
- [x] Add a new string resource and use it for a TextView
- [x] Create a string-array resource
- [x] Create a string resource that has an ampersand in it (note: don't just use the & char!)

**Comment by jesse-digregorio** [comment]
Made these changes in this commit: https://github.com/jesse-digregorio/AndroidTinker/commit/e026aa0a38cfd035ad23df8579604ffeb74fcbd5
